version: '3.9'

services:
  backend:
    build: .
    container_name: synthara-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./scripts:/app/scripts
      - ./database:/app/database
    env_file:
      - .env.example
    depends_on:
      - db

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: synthara-web
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    container_name: synthara-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
      - backend

  db:
    image: postgres:14
    container_name: synthara-db
    environment:
      POSTGRES_USER: synthara
      POSTGRES_PASSWORD: synthpass
      POSTGRES_DB: synthara_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: